### ISSUE TITLE
gitee.com\johng\gf-demos\app\ctl\chat\chat.go

### ISSUE THREAD

**Issue by ywanbing** [gogf/gf-demo-user#1]
// 向客户端返回用户列表
func (c *Controller) writeUsers() error {
	array := garray.NewSortedStringArray(0, false, false) //这里的 第二个参数不对 原来是0 
	names.Iterator(func(v string) bool {
		array.Add(v)
		return true
	})
	if err := c.writeGroup(Msg{"list", array.Slice(), ""}); err != nil {
		return err
	}
	return nil
}

**Comment by gqcn** [comment]
@ywanbing 感谢反馈，已修复。
