### ISSUE TITLE
gf 脚手架问题

### ISSUE THREAD

**Issue by 957651480** [gogf/gf-demo-user#14]
脚手架取名太随意了，拉下来每个文件都得改mod

**Comment by gqcn** [comment]
@957651480 麻烦具体描述一下问题呢？

**Comment by 957651480** [comment]
go 不是用mod 来管理依赖吗，你脚手架用gf-demos来命名，拉下来的代码里面就会包含类似gf-demos的包名，又得自己修改一遍，大部分开发者都会用fork 的方式来同步脚手架，建议用公用的项目包名。虽然说有gf 工具，但没这种方式好。

**Comment by gqcn** [comment]
@957651480 `gf-demos`示例仓库使用的包名是`github.com/gogf/gf-demos`，这个项目是完整项目示例，不是作为引用包设计的。脚手架工具是`gf-cli`，文档介绍地址：https://goframe.org/toolchain/cli
