### ISSUE TITLE
看go文档，一般来讲，Tag 都是以 key:"value" 这种键值对的形式，如果有多个键值对，则以空格分隔。但在本代码处，不大懂tag为什么这么写，依据是在哪里，希望请教您一下

### ISSUE THREAD

**Issue by wthahaha** [gogf/gf-demo-user#19]
https://github.com/gogf/gf-demos/blob/9e2428b4852ae3bb93ba51e2226be452e19473e3/app/model/user.go#L15

**Comment by gqcn** [comment]
@cncert 哈哈，麻烦仔细看下这就是`key:"value"`键值对类型
