### ISSUE TITLE
gf-demo在windows 10和go1.12.5环境下运行没反应

### ISSUE THREAD

**Issue by arden** [gogf/gf-demo-user#5]
gf-demo在windows 10和go1.12.5环境下运行没反应，我测试了好几次，用gf 1.6.14 / gf 1.6.15 都可以，但是用gf 1.6.16 就不行，有群友反应在go.mod下运行有问题，但是在gopath模式下运行就正常。

**Comment by gqcn** [comment]
@arden 请用最新版本试试。
