### ISSUE TITLE
我这边在测试demo的时候遇到几个问题

### ISSUE THREAD

**Issue by zj77086539** [gogf/gf-demo-user#7]
1.tmplate 中模板标记不生效${include .tplMain .}
2.需要自己手动修改config
3.chat.go  cache.SetIfNotExist  聊天消息时间间隔不生效

**Comment by ringlog** [comment]
> 1.tmplate 中模板标记不生效${include .tplMain .}
> 2.需要自己手动修改config
> 3.chat.go cache.SetIfNotExist 聊天消息时间间隔不生效

同第一个问题

**Comment by lee997** [comment]
同遇上模板解析标签问题

项目为 gf init生成的项目, 配置文件config.toml里模板默认配置为

[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]


官方example里对模板的解析为 {{   }}

需要修改使用方式或者配置

[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]
